# config/model/atn_pooling.yaml

name: "atn_pooling"

model_class: "src.model.cox_mil_resnet.CoxAttentionResnet"

hparams:
  resnet:
    dim: 2
    in_features: 1
    kernel_size: 5
    stem_kernel_size: 17
    blocks: [1, 1, 1]
    features: [8, 16, 32]
    activation: "LReLU"
    downsampling_factor: 2
    normalization: "BatchN"
    preactivation: false
    trace_stages: true

  mil_head:
    input_size: 32
    hidden_size: 32
    attention_hidden_size: 16
    output_size: 1
    dropout: true
    dropout_prob: ${training.hparams.dropout_prob}
