name: "atn_pooling_feedforward"

model_class: "src.model.feedforward_mil.AFibAttentionNet"

hparams:
  input_size: 1
  hidden_size: 64
  attention_hidden_size: 32
  output_size: 1
  dropout: true
  dropout_prob: ${training.hparams.dropout_prob}