name: "edge_conv_gnn"

model_class: "src.model.graph_nn.DynamicEdgeConvGNN"  

hparams:
  in_channels: 8
  conv_channels: [16, 32]
  embedding_dims: [128]
  k: 10
  aggr: "max"
  activation: "leakyrelu"
  use_bn: false
  graph_recompute: false
  pooling: "mean"
  classifier_dims: [64, 32]
  dropout: 0.3