# ------------------------------------------------------------------
# Team Standard Environment: "Base"
# Python: 3.12
# PyTorch: 2.9.x (Latest Stable, Oct 2025)
# CUDA: 12.6 (via pytorch-cuda)
# ------------------------------------------------------------------
name: ml-base-py312

channels:
  # Priority: pytorch, then nvidia, then conda-forge
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.12.*
  - pip

  # ----- PyTorch Stack -----
  - pytorch=2.9.*
  - torchvision=0.24.*
  - torchaudio=2.9.*
  - pytorch-cuda=12.1


  # ----- ML/Data science Stack -----
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn=1.5.*
  - scipy=1.14.*
  - matplotlib
  - seaborn
  - psycopg2  # PSQL adapter
  - sqlalchemy
  - transformers

  # ----- Data formats -----
  - h5py
  - pyaml

  # ----- MLOps -----
  - mlflow
  - hydra-core
  # - datasets
  # - accelerate

  # ----- Other -----
  - tqdm
  - python-dotenv

  # ----- PIP-only packages -----
  - pip:
    - wandb
    - hydra-optuna-sweeper
    - torchsurv
    - torchtuples
