# config/config.yaml

defaults:
  - _self_
  - model: graph_nn
  - data/paths: paths
  - data/dataset: graph_dataset
  - data/transforms: amplitude_norm
  - training/task: survival
  - training/hparams: hparams
  - training/loss: coxph
  - training/optimizer: adamw
  - training/scheduler: cosine
  - training/label_transforms: label_noise

study_name: "WMP2"
experiment_name: "graph_nn_tryout"
run_name: "all_points_radius_7_mm_aggr_sum"
seed: 220920
folds: 3