# config/config.yaml

defaults:
  - _self_
  - model: graph_nn
  - data/paths: paths
  - data/dataset: graph_dataset
  - data/transforms: no_transforms
  - training/task: survival
  - training/hparams: hparams
  - training/loss: cox
  - training/optimizer: adamw
  - training/scheduler: cosine

study_name: "WMP2"
experiment_name: "eliminated_bad_cases"
run_name: "graph_attention_survival"
seed: 250325
folds: 3